# roles/ansible-controller/tasks/main.yml
---

- name: Install packages required for managing a Kubernetes cluster
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items:
  - libselinux-python
  - python-netaddr
  - ipmitool
  - net-tools
  tags: ansible-controller

- name: Create Ansible temp directory
  file: path={{ ansible_temp_dir }} state=directory

- name: Create apache user
  user: name=apache state=present  

- name: Create apache group
  group: name=apache state=present

- name: Create download directory
  file:
    path: "{{ download_dir }}"
    state: directory
    owner: apache
    group: apache
    mode: '0701'

- include: flannel_download.yml
  when: manage_flannel_download

- include: kube_download.yml
  when: manage_kube_download

- include: pypy_download.yml
  when: manage_pypy_download

#TODO add code for downloading other files such
# as addons, systemd unit files
# - include: kube_addons_download.yml
#  when: manage_kube_addons_download
